# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'dispatch_semaphore' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dispatch_semaphore
  pod 'AFNetworking', '~> 3.1.0'

  target 'dispatch_semaphoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dispatch_semaphoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
