# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'A' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for A
  pod 'SAMKeychain'
  target 'ATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
